name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10
    - uses: mpetrunic/swagger-cli-action@v1.0.0
      with:
        command: "bundle ./beacon-node-oapi.yaml -r -t json -o ./beacon-node-oapi.json"
    - name: Generate TypeScript
      run: npx @openapitools/openapi-generator-cli generate -i ./beacon-node-oapi.json -g typescript-node -o ./generated-typescript
    - run: mv npm-package.json package.json
    - name: Publish if version has been updated
      uses: JS-DevTools/npm-publish@v1 
      with: # All of theses inputs are optional
        token: ${{ secrets.NPM_TOKEN }}
        dry-run: true
